### ISSUE TITLE
Inquiry of Ownership

### ISSUE THREAD

**Issue by AustinLeath** [Percdye7/percdye7.github.io#1]
Hello! I am the community admin for https://www.r6tab.com and I would like to inquire to exactly what the r6tab app that you have made actually does. We are a closed source group and would like figure out exactly what your app does. We cannot download it because it crashes.

**Comment by AustinLeath** [comment]
@Percdye7 It has been over a week now and no reply, I am trying to inquire as to what your r6tab app actually does. Please reply to me here as soon as possible so we can get this issue sorted out. Thanks!

**Comment by Percdye7** [comment]
Hello Austin

First of all, I am deeply sorry that i never replied to you. The reason i never replied is because i actually never got any notification that you tried to contact me.

Today i got an E-Mail from github and that was the first time i saw your opened ticket.

Iam here to answer you any questions, so feel free to contact me again

**Comment by AustinLeath** [comment]
Hey no big deal. This was a long time ago. I am gonna go ahead and close this issue.
